ChalacteosApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.contabilidad.urls', namespace='contabilidad'), name='contabilidad'),
    path('', include('apps.inventario.urls', namespace='inventario'), name='inventario'),
    path('',include('apps.planilla.urls', namespace='planilla'), name='planilla'),
    path('costeo/',include('apps.costeo.urls', namespace='costeo'), name='costeo')
]

apps/costeo/urls.py
from django.conf.urls import url,include

from . import views

app_name = 'costeo'
urlpatterns = [
    path(
		'crear/boleta/',
		views.BoletaCreateView.as_view(),
		name='boleta-crear'
	),
]

apps/inventario/urls.py
from django.urls import path, re_path

from . import views

app_name = 'inventario'
urlpatterns = [
	path(
		'import/cliente/',
		views.import_data_cliente,
		name='import-cliente'
	),
	path(
		'import/proveedor/',
		views.import_data_proveedor,
		name='import-proveedor'
	),
	path(
		'import/recursos/',
		views.import_data_recursos,
		name='import-recursos'
	),
	path(
		'import/materias/',
		views.import_data_materia,
		name='import-materias'
	),
	path(
		'import/impuestos/',
		views.import_data_impuesto,
		name='import-impuesto'
	),
	path(
		'proveedores/',
		views.ProveedoresListView.as_view(),
		name='proveedores'
	),
	path(
		'clientes/',
		views.ClientesListView.as_view(),
		name='clientes'
	),
	path(
		'ventas/',
		views.VentasListView.as_view(),
		name='ventas'
	),
	path(
		'compras/',
		views.ComprasListView.as_view(),
		name='compras'
	),
	path(
		'materiales/',
		views.MateriasPrimasListView.as_view(),
		name='materia-prima'
	),
	path(
		'impuestos/',
		views.ImpuestosListView.as_view(),
		name='impuestos'
	),
	re_path(
		r'kardex/(?P<id_kardex>[0-9]+)/',
		views.get_movimientos,
		name='kardex'
	),
	path(
		'crear/proveedor/',
		views.ProveedorCreateView.as_view(),
		name='proveedor-crear'
	),
	path(
		'crear/cliente/',
		views.ClienteCreateView.as_view(),
		name='cliente-crear'
	),
	path(
		'crear/venta/',
		views.VentaCreateView.as_view(),
		name='venta-crear'
	),
	path(
		'crear/compra/',
		views.CompraCreateView.as_view(),
		name='compra-crear'
	),
	path(
		'crear/impuesto/',
		views.ImpuestoCreateView.as_view(),
		name='impuesto-crear'
	),
	path(
		'crear/material/',
		views.MateriaPrimaCreateView.as_view(),
		name='material-crear'
	),
	path(
		'edicion/proveedor/<slug:pk>/',
		views.ProveedorUpdateView.as_view(),
		name='proveedor-edicion'
	),
	path(
		'edicion/cliente/<slug:pk>/',
		views.ClienteUpdateView.as_view(),
		name='cliente-edicion'
	),
	path(
		'edicion/impuesto/<slug:pk>/',
		views.ImpuestoUpdateView.as_view(),
		name='impuesto-edicion'
	),
	path(
		'edicion/material/<slug:pk>/',
		views.MateriaPrimaUpdateView.as_view(),
		name='materia_prima-edicion'
	),
	path(
		'detalle/proveedor/<slug:pk>/',
		views.ProveedorDetailView.as_view(),
		name='proveedor-detalle'
	),
	path(
		'detalle/cliente/<slug:pk>/',
		views.ClienteDetailView.as_view(),
		name='cliente-detalle'
	),
	path(
		'detalle/impuesto/<slug:pk>/',
		views.ImpuestoDetailView.as_view(),
		name='impuesto-detalle'
	),
	path(
		'detalle/material/<slug:pk>/',
		views.MateriaPrimaDetailView.as_view(),
		name='materia-prima-detalle'
	),
	re_path(
		r'detalle/compra/(?P<id_compra>[0-9]+)/',
		views.get_compra,
		name='materia-compra'
	),
	re_path(
        r'ajax/proveedor/(?P<id_proveedor>[0-9]+)/',
        views.proveedores,
        name='ajax-proveedor'
    ),
    re_path(
        r'ajax/cliente/(?P<id_cliente>[0-9]+)/',
        views.clientes,
        name='ajax-cliente'
    ),
    re_path(
        r'ajax/impuesto/(?P<id_impuesto>[0-9]+)/',
        views.impuestos,
        name='ajax-impuesto'
    ),
    re_path(
        r'ajax/materiaprima/(?P<id_materia_prima>[0-9]+)/',
        views.materiales,
        name='ajax-materia-prima'
    ),
	path(
		'ajax/compra/',
		views.CompraCreateView.as_view(),
		name='ajax-compra'
	),
    re_path(
		'ajax/load/materia/',
		views.load_materia,
		name='ajax-materia'
	),
	path(
		'ajax/venta/',
		views.VentaCreateView.as_view(),
		name='ajax-venta'
	),
]

apps/planilla/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from apps.contabilidad.models import Empresa


class Departamento(models.Model):
	id_departamento = models.AutoField(
		primary_key=True
	)
	empresa = models.ForeignKey(
		Empresa,
		verbose_name='Empresa',
		on_delete=models.DO_NOTHING,
		blank=False,
		default=0,
		null=False
	)
	nombre = models.CharField(
		verbose_name='Nombre del Departamento',
		max_length=40,
		null=False, 
		blank=False,
		help_text='Ingrese el nombre del departamento'
	)
	descripcion = models.TextField(
		verbose_name='Descripcion del Departamento',
		max_length=250,
		null=True, 
		blank=True,
		help_text='Ingrese una descripcion del departamento'
	)

	class Meta:
		verbose_name = 'Departamento'
		verbose_name_plural = 'Departamentos'
		unique_together = ("id_departamento", "nombre")
		ordering= ["id_departamento"]

	def __str__(self):
		return '%s' % (self.nombre)

class Puesto(models.Model):
	id_puesto = models.AutoField(
		primary_key=True
	)
	departamento = models.ForeignKey(
		Departamento,
		verbose_name='Departamento',
		on_delete=models.DO_NOTHING,
		blank=False,
		default=0,
		null=False,
		help_text='Seleccione el departamento'
	)
	codigo_puesto = models.CharField(
		verbose_name='Codigo del puesto',
		max_length=50,
		null=False,
		help_text='Ingrese el codigo del puesto',
		blank=False
	)
	nombre_funcional = models.CharField(
		verbose_name='Nombre del Puesto',
		max_length=50, 
		null=False, 
		blank=False,
		help_text='Ingrese el nombre del puesto'
	)
	descripcion = models.TextField(
		verbose_name='Descripcion del Puesto',
		max_length=50, 
		help_text='Ingrese una descripcion del puesto'
	)
	salario_base = models.DecimalField(
		verbose_name='Salario de un Puesto',
		max_digits=6, 
		decimal_places=2, 
		null=False, 
		blank=False,
		validators=[
			MinValueValidator(
				0, 
				message='Este campo debe ser positivo'
			)
		],
		help_text='Ingrese el salario para este puesto'
	)

	class Meta:
		verbose_name = 'Puesto'
		verbose_name_plural = 'Puestos'
		unique_together = ("codigo_puesto", "nombre_funcional")
		ordering= ["id_puesto"]
 

	def __str__(self):
		return ' %s' % (self.nombre_funcional)


class Empleado(models.Model):
	empleado = models.OneToOneField(
		User,
		on_delete=models.CASCADE
	)
	puesto = models.ForeignKey(
		Puesto,
		verbose_name='Puesto',
		on_delete=models.DO_NOTHING,
		blank=False,
		null=True
	)
	dui = models.CharField(
		verbose_name='DUI',
		max_length=10, 
		null=True, 
		blank=False,
		help_text='Ingrese el Documento Único de Identidad del empleado' 
	)
	fecha_nacimiento = models.DateField(
		verbose_name='Fecha de nacimiento',
		null=True, 
		blank=False,
		help_text='Ingrese el segundo apellido de la persona' 
	)
	telefono = models.IntegerField(
		verbose_name='Numero de telefono',
		null=True, 
		blank=False,
		help_text='Ingrese el telefono'
	)
	direccion = models.CharField(
		verbose_name='Direccion',
		max_length=50,
		help_text='Ingrese la direccion',
		null=True
	)
	is_active = models.BooleanField(
		verbose_name='¿El empleado está de alta?',
		default=True,
		help_text='Active esta casilla para mantener de alta al empleado'
	)

	class Meta:
		verbose_name = 'Empleado'
		verbose_name_plural = 'Empleados'
		ordering= ["puesto", 'dui']

	def __str__(self):
		return '%s %s' % (self.empleado.first_name, self.empleado.last_name)

	@receiver(post_save, sender=User)
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			Empleado.objects.create(empleado=instance)

	@receiver(post_save, sender=User)
	def save_user_profile(sender, instance, **kwargs):
		instance.empleado.save()

apps/costeo/forms.py
from django import forms

from .models import *

class BoletaTrabajoForm(forms.ModelForm):
    scope_prefix = 'boleta_data'
    form_name = 'boleta_form'
    class Meta:
        model = BoletaTrabajo
        fields = [
            'numero_horas',
			'monto_horas'
        ]

    def __init__(self, *args, **kwargs):
        super(DetalleCompraForm, self).__init__(*args,**kwargs)
        self.fields['numero_horas'].widget.attrs.update({'min':'0'})
        self.fields['monto_horas'].widget.attrs.update({'min':'0', 'step':0.01})

class RequisicionForm(forms.ModelForm):
    scope_prefix = 'requisicion_data'
    form_name = 'requisicion_form'
    class Meta:
        model = RequisicionMaterial
        fields = [
            'cantidad_material',
			'costo_total_material'
        ]

    def __init__(self, *args, **kwargs):
        super(DetalleCompraForm, self).__init__(*args,**kwargs)
        self.fields['cantidad_material'].widget.attrs.update({'min':'0'})
        self.fields['costo_total_material'].widget.attrs.update({'min':'0', 'step':0.01})

apps/inventario/forms.py
from django import forms

from .models import *


class VentaForm(forms.ModelForm):
    scope_prefix = 'venta_data'
    form_name = 'venta_form'
    class Meta:
        model = Venta
        fields = [
            'id_cliente'
        ]


class MovimientoForm(forms.ModelForm):
    scope_prefix = 'movimiento_data'
    form_name = 'movimiento_form'
    class Meta:
        model = Movimiento
        fields = [
            'costo_unitario_movimiento'
        ]


class RecursoProductoForm(forms.ModelForm):
    scope_prefix = 'producto_data'
    form_name = 'producto_form'

    class Meta:
        model = Recurso
        fields = [
            'nombre_recurso'
        ]


class DetalleVentaForm(forms.ModelForm):
    scope_prefix = 'detalle_venta_data'
    form_name = 'detalle_venta_form'
    class Meta:
        model = Detalle
        fields = [
            'cantidad_detalle'
        ]

    def __init__(self, *args, **kwargs):
        super(DetalleVentaForm, self).__init__(*args,**kwargs)
        self.fields['cantidad_detalle'].widget.attrs.update({'min':'0'})


class CompraForm(forms.ModelForm):
    scope_prefix = 'compra_data'
    form_name = 'compra_form'

    class Meta:
        model = Compra
        fields = [
            'id_proveedor'
        ]


class DetalleCompraForm(forms.ModelForm):
    scope_prefix = 'detalle_compra_data'
    form_name = 'detalle_compra_form'
    precio_unitario = forms.DecimalField(
        label='Precio unitario',
        help_text='Ingrese el precio unitario usando coma decimal',
        decimal_places=2
    )
    class Meta:
        model = Detalle
        fields = [
            'id_materia_prima',
            'cantidad_detalle',
            'precio_unitario'
        ]

    def __init__(self, *args, **kwargs):
        super(DetalleCompraForm, self).__init__(*args,**kwargs)
        self.fields['cantidad_detalle'].widget.attrs.update({'min':'0'})
        self.fields['precio_unitario'].widget.attrs.update({'min':'0', 'step':0.01})
        self.fields['id_materia_prima'].choices = (('', '---------'),)
        self.fields['id_materia_prima'].widget.attrs.update({'disabled': 'true'})


class RecursoForm(forms.ModelForm):
    scope_prefix = 'recurso_data'
    form_name = 'recurso_form'

    class Meta:
        model = Recurso
        fields = [
            'nombre_recurso',
            'descripcion_recurso'
        ]


class MateriaPrimaForm(forms.ModelForm):
    scope_prefix = 'materia_prima_data'
    form_name = 'materia_prima_form'

    class Meta:
        model = MateriaPrima
        fields = [
            'id_materia_prima'
        ]


class ProveedorCompraForm(forms.ModelForm):
    scope_prefix = 'proveedor_data'
    form_name = 'proveedor_form'
    is_credito = forms.BooleanField(
        label='¿La compra es al crédito?',
        help_text='Indique si está factura será pagada al crédito ya sea total o parcialmente'
    )
    is_contado = forms.BooleanField(
        label='¿La compra es al contado?',
        help_text='Indique si está factura será pagada al contado ya sea total o parcialmente'
    )
    proporcion = forms.DecimalField(
        label='Proporcion',
        help_text='Ingrese la proporcion de la compra que será al credito',
        decimal_places=2
    )
    class Meta:
        model = Proveedor
        fields = [
            'nombre_proveedor',
            'is_credito',
            'is_contado',
            'proporcion'
        ]

    def __init__(self, *args, **kwargs):
        super(ProveedorCompraForm, self).__init__(*args,**kwargs)
        self.fields['nombre_proveedor'] = forms.ModelChoiceField(
            label='Proveedor',
            queryset=Proveedor.objects.all(),
            help_text='Seleccione el proveedor al que se le comprará la materia prima',
            widget=forms.Select(
                attrs={
                    'onchange': 'getMateria("id_nombre_proveedor", "id_id_materia_prima")'
                }
            )
        )
        self.fields['proporcion'].widget.attrs.update({
            'min':'0',
            'max':'100',
            'step':0.01,
            'disabled':True
        })
        self.fields['is_contado'].widget.attrs.update({'onchange':'getCheckbox()', 'checked': 'checked'})
        self.fields['is_credito'].widget.attrs.update({'onchange':'getCheckbox()'})


class ProveedorForm(forms.ModelForm):
    scope_prefix = 'proveedor_data'
    form_name = 'proveedor_form'

    class Meta:
        model = Proveedor
        fields = [
            'nombre_proveedor'
        ]

    def __init__(self, *args, **kwargs):
        super(ProveedorForm, self).__init__(*args,**kwargs)
        self.fields['nombre_proveedor'] = forms.ModelChoiceField(
            label='Proveedor',
            queryset=Proveedor.objects.all(),
            help_text='Seleccione el proveedor al que se le comprará la materia prima',
        )


class ClienteVentaForm(forms.ModelForm):
    scope_prefix = 'cliente_data'
    form_name = 'cliente_form'
    is_credito = forms.BooleanField(
        label='¿La venta es al crédito?',
        help_text='Indique si está factura será pagada al crédito ya sea total o parcialmente'
    )
    is_contado = forms.BooleanField(
        label='¿La venta es al contado?',
        help_text='Indique si está factura será pagada al contado ya sea total o parcialmente'
    )
    proporcion = forms.DecimalField(
        label='Proporcion',
        help_text='Ingrese la proporcion de la venta que será al credito',
        decimal_places=2
    )
    class Meta:
        model = Cliente
        fields = [
            'nombre_cliente',
            'is_credito',
            'is_contado',
            'proporcion'
        ]

    def __init__(self, *args, **kwargs):
        super(ClienteVentaForm, self).__init__(*args,**kwargs)
        self.fields['nombre_cliente'] = forms.ModelChoiceField(
            label='Cliente',
            queryset=Cliente.objects.all(),
            help_text='Seleccione el cliente al que se le venderá el producto',
        )
        self.fields['proporcion'].widget.attrs.update({
            'min':'0',
            'max':'100',
            'step':0.01,
            'disabled':True
        })
        self.fields['is_contado'].widget.attrs.update({'onchange':'getCheckbox()', 'checked': 'checked'})
        self.fields['is_credito'].widget.attrs.update({'onchange':'getCheckbox()'})
 

apps/costeo/views.py
from django.shortcuts import render

from django.views.generic import CreateView, TemplateView 
from django.views.generic.list import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.forms.models import model_to_dict
from django.template import loader
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import *
from .forms import *
from apps.planilla import views as planilla
from apps.contabilidad import views as conta

class OrdenCreateView(LoginRequiredMixin, TemplateView):
	template_name = 'costeo/chainedOrdenForm.html'
	success_url = reverse_lazy('costeo:orden')
	
	def get(self, request, *args, **kwargs):
		context = self.get_context_data(**kwargs)
		empresa = conta.Empresa.objects.get(id_empresa=1)
		departamento = planilla.departamento.objects.get(id_departamento=empresa.id_departamento)
		
		

class BoletaCreateView(LoginRequiredMixin, TemplateView):
	template_name = 'costeo/chainedBoletaTrabajoForm.html'
	success_url = reverse_lazy('costeo:boleta')

	def get_context_data(self, **kwargs):
		context = super(BoletaCreateView,self).get_context_data(**kwargs)
		empresa = conta.Empresa.objects.get(id_empresa=1)
		if 'empresa_form' not in context:
			context['empresa_form'] = planilla.EmpresaForm(instance=empresa)
		context['id_empresa'] = empresa
		return context

	def get(self, request, *args, **kwargs):
		context = self.get_context_data(**kwargs)
		context['boleta_form'] = BoletaTrabajoForm()
		context['departamento_form'] = planilla.DepartamentoForm()
		return self.render_to_response(context)

	def post():
		pass


class RequisicionCreateView(LoginRequiredMixin, TemplateView):
	template_name = 'costeo/chainedRequisionMPForm.html'
	success_url = reverse_lazy('costeo:orden')

	def get_context_data(self, **kwargs):
		context = super(BoletaCreateView,self).get_context_data(**kwargs)
		empresa = conta.Empresa.objects.get(id_empresa=1)
		if 'empresa_form' not in context:
			context['empresa_form'] = planilla.EmpresaForm(instance=empresa)
		context['id_empresa'] = empresa
		return context

	def get(self, request, *args, **kwargs):
		context = self.get_context_data(**kwargs)
		context['requisicion_form'] = RequisicionForm()
		context['departamento_form'] = planilla.DepartamentoForm()
		return self.render_to_response(context)

templates/costeo/chainedBoletaTrabajoForm.html
{% extends 'header&footer.html' %}
{% block title %}SCIeL - Edición / {% endblock title %}

{% block content %}
  
  {% block sidebar %}
    {% include 'sidebarInventario.html' %}
  {% endblock sidebar %}
  {% block tables %}
  {% load bootstrap %}
  {% load l10n %}
    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Edición  | Creación</a>
          </li>
          <li class="breadcrumb-item active">Ingreso de Datos</li>
        </ol>
        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-edit"></i>
                Edición | Creación
            <i class="fas fa-plus-circle"></i>
          </div>
          <div class="card-body" id="1">
            <div>
              <div class="col-lg-12 col-xs-12 border rounded">
                <form name="compra_form" novalidate>
                {% csrf_token %}
                  <div class="row">
                    <div class="col-lg-6 col-xs-12">
                      <h4 class="mb-3 text-center header_id">EMPRESA</h4>
                      {{ empresa_form|bootstrap_inline }}
                      {{ departamento_form|bootstrap_inline }}
                    </div>
                    <br>
                    <div  class="col-lg-6 col-xs-12">
                      <h4 class="mb-3 text-center header_id">BOLETA DE TRABAJO</h4>
                      {{ boleta_form|bootstrap_inline }}
                    </div>
                  </div>
                  <div class="col-12 text-center">    
                    <button class="btn btn-outline-primary btn-plus" onclick="getData()" type="button">
                      Registrar requision 
                      <i class="fas fa-plus-circle"></i>
                    </button>
                  </div><br>
                </form>
              </div>
            </div>
        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Boleta de trabajo
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <td colspan="2">Empresa:</td>
                  </tr>
                  <tr>
                    <tr class="text-center">
                      <td colspan="1">No. de orden: </td>
                      <td colspan="2"></td>
                    </tr>
                    <tr class="text-center">
                      <td colspan="1">Fecha: </td>
                      <td colspan="2">Departamento: </td>
                    </tr>
                    <tr class="text-center">
                      <td colspan="1">Hora comienzo</td>
                      <td colspan="2">Nombre empleado: </td>
                    </tr>
                    <tr class="text-center">
                      <td colspan="1">Hora finalización</td>
                      <td colspan="2">Salario por hora </td>
                    </tr>
                    <tr class="text-center">
                      <td colspan="1">Total de horas</td>
                      <td colspan="2">Monto total</td>
                    </tr>
                  </tr>
                </thead>
            </table>
                </div>
              </div>
            </div>
            <div class="form-group text-center">
              <br>
              <button id='aprobar' type="submit" onclick="sendData()" class='btn btn-primary' style="width: 30%" href='#'>Guardar</button>
              <button class='btn btn-secondary' onclick="javascript:history.back()" style="width: 30%" type='button'>Cancelar</button>                    
            </div>
          </div>
            <script>
              //Declarando variable globales
              var count = 0;
              var totalVenta = 0;
              var subTotalVenta = 0;
              var totalFila = 0;
              var empleado = "";
              var cantidad = 0;
              var empresa = "";
              var codigoEmpleado = null;
              
              function getData(){
                console.log("ADDROWS")
                count = count + 1;
                codigoCliente = $("#id_nombre_cliente").val();
                codigoDepartamento = $("#id_nombre").val();
                var cbEmpleado = document.getElementById("id_nombre");
                var cbDepartamento = document.getElementById("id_nombre");

                empleado = cbEmpleado.options[cbEmpleado.selectedIndex].text;
                departamento = cbDepartamento.options[cbDepartamento.selectedIndex].text;                
                
                cantidad = parseInt($("#id_cantidad").val());
                var precio = parseFloat($("#id_costo_unitario_movimiento").val());
                if(getCheckbox()){
                  proporcion =  parseFloat($("#id_proporcion").val());
                }
                if(cliente!='' && cliente!='---------' && producto!='' && !isNaN(cantidad) && !isNaN(precio)){
                    addRows(cliente, producto, cantidad, precio);
                }
              };
              
              function addRows(cliente, producto, cantidad, precio){
                console.log("registro")
                totalFila=round(cantidad*precio);
                //totales+=totalFila+",";
                subTotalVenta=round((subTotalVenta+totalFila));
                iva=round(subTotalVenta*parseFloat({{impuesto.tasa_impuesto|stringformat:'f'}}));
                totalVenta=round(subTotalVenta*(1+parseFloat({{impuesto.tasa_impuesto|stringformat:'f'}})));
                if(isCredito && isContado){
                  credito = round(totalVenta*proporcion/100);
                  contado = round(totalVenta*(1-proporcion/100));
                }else{
                  if(isCredito){
                    credito = totalVenta;
                  }else{
                    contado = totalVenta;
                  }
                }
                console.log("CANTIDAD");
                $("#tbBody").append(
                  "<tr><td class='text-center'>"+count+"</td>"+
                  "<td>"+cliente+"</td>"+
                  "<td>"+producto+"</td>"+
                  "<td class='text-center'>"+cantidad+"</td>"+
                  "<td class='text-center'>$ "+precio+"</td>"+
                  "<td class='text-center'>$ "+totalFila+"</td></tr>"
                );
                $("#subTotal").empty();
                $("#subTotal").append("$ "+subTotalVenta);
                $("#iva").empty();
                $("#iva").append("$ "+iva);
                $("#contado").empty();
                $("#contado").append("$ "+contado);
                $("#credito").empty();
                $("#credito").append("$ "+credito);
                $("#total").empty();
                $("#total").append("$ "+totalVenta);
              }
              function round(number){
                number = Math.round(number*100)/100;
                return number;
              };
              
            function sendData() {
              var data = {}
              if(totalVenta > 0){
                if(isCredito && isContado){
                  data = {
                    'totalVenta': subTotalVenta,
                    'totalFila': totalFila,
                    'cliente': cliente,
                    'producto': producto,
                    'cantidad': cantidad,
                    'proporcion': proporcion
                  }
                }else{
                  data = {
                    'totalVenta': subTotalVenta,
                    'totalFila': totalFila,
                    'cliente': cliente,
                    'producto': producto,
                    'cantidad': cantidad,
                    'isCredito': isCredito
                  }
                }
                $.ajax({
                  url: '{% url 'inventario:venta-crear' %}',
                  type: 'POST',
                  data: data,
                  success: function(data){
                    console.log(data);
                    console.log("SUCCESS");
                  },
                  dataType: 'json'
                }).done(function(data){
                  alert(data.message)
                  location.href = data.success_url;
                }).fail(function(data) {
                  console.log("error");
                  console.log(data.message);
                }).always(function() {
                  console.log("complete");
                });
              }
            }
          </script>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  {% endblock tables %}
    
{% endblock content %}

templates/costeo/chainedOrdenForm.html
{% extends 'header&footer.html' %}
{% block title %}SAeL - Gestión de Clientes{% endblock title %}

{% block content %}    
  {% block sidebar %}
    {% include 'sidebarCosteo.html' %}
  {% endblock sidebar %}
  {% block tables %}
    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Orden de fabricacion</a>
          </li>
          <li class="breadcrumb-item active">Orden de fabricacion</li>
        </ol>
        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Orden de fabricacion
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <td colspan="10"># orden de fabricacion</td>
                  </tr>
                  <tr>
                    <td colspan="10">Departamento</td>
                  </tr>
                  <tr>
                    <tr class="text-center">
                      <th rowspan="2" style="vertical-align: middle !important">Fecha</th>
                      <th colspan="3" style="vertical-align: middle !important">Materiales</th>
                      <th colspan="3" style="vertical-align: middle !important">Mano de pobra</th>
                      <th colspan="3" style="vertical-align: middle !important">CIF</th>
                    </tr>
                    <tr class="text-center">
                      <th style="vertical-align: middle !important">Materia</th>
                      <th style="vertical-align: middle !important">Cantidad</th>
                      <th style="vertical-align: middle !important">Precio unitario</th>
                      <th style="vertical-align: middle !important">#Obrero </th>
                      <th style="vertical-align: middle !important<"Importe"</th>
                      <th style="vertical-align: middle !important">Cantidad</th>
                      <th style="vertical-align: middle !important">Costo Unitario</th>
                      <th style="vertical-align: middle !important">Tasa</th>
                      <th style="vertical-align: middle !important">Importe</th>

                    </tr>
                  </tr>
                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  {% endblock tables %}
    
{% endblock content %}