ChalacteosApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.contabilidad.urls', namespace='contabilidad'), name='contabilidad'),
    path('', include('apps.inventario.urls', namespace='inventario'), name='inventario'),
    path('',include('apps.planilla.urls', namespace='planilla'), name='planilla'),
    path('costeo/',include('apps.costeo.urls', namespace='costeo'), name='costeo')
]

apps/contabilidad/urls.py
from django.conf.urls import include
from django.urls import reverse_lazy, path, re_path
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from . import views

app_name ='contabilidad'

urlpatterns = [
	path(
		'',
		views.IndexView.as_view(),
		name='index'
	),
	path(
		'import/rubro/',
		views.import_data_rubro,
		name='import-rubro'
	),
	path(
		'import/cuenta/',
		views.import_data_cuenta,
		name='import-cuenta'
	),
	path(
		'import/transaccion/',
		views.import_data_transaccion,
		name='import-transaccion'
	),
	re_path(
		'sign-in/',
		views.SignInView.as_view(),
		name='sign-in'
	),
	path(
        'sign-out/',
        views.SignOutView.as_view(),
        name='sign-out'
    ),
	path(
		'cuentas/',
		views.CuentasListView.as_view(),
		name='cuentas'
	),
	path(
		'crear/cuenta/',
		views.CuentaCreateView.as_view(),
		name='cuenta-crear'
	),
	path(
		'edicion/cuenta/<slug:pk>/',
		views.CuentaUpdateView.as_view(),
		name='cuenta-edicion'
	),
	path(
		'detalle/cuenta/<slug:pk>/',
		views.CuentaDetailView.as_view(),
		name='cuenta-detalle'
	),
	path(
		'estados/',
		views.EstadoFinancieroListView.as_view(),
		name='estados-financieros'
	),
	path(
		'detalle/estado/general/<slug:pk>/',
		views.BalanceGeneralDetailView.as_view(),
		name='balance-general-detalle'
	),
	path(
		'detalle/estado/resultados/<slug:pk>/',
		views.EstadoResultadosDetailView.as_view(),
		name='balance-resultados-detalle'
	),
	path(
		'detalle/estado/capital/<slug:pk>/',
		views.EstadoCapitalDetailView.as_view(),
		name='balance-capital-detalle'
	),
	path(
		'detalle/estado/comprobacion/<slug:pk>/',
		views.BalanceComprobacionDetailView.as_view(),
		name='balance-comprobacion-detalle'
	),
	re_path(
        r'ajax/cuenta/(?P<id_cuenta>[0-9]+)/',
        views.cuentas,
        name='ajax-cuenta'
    ),
	path(
		'transacciones/',
		views.TransaccionesListView.as_view(),
		name='transacciones'
	),
	path(
		'crear/transaccion/',
		views.TransaccionCreateView.as_view(),
		name='transaccion-crear'
	),
	path(
		'edicion/transaccion/<slug:pk>/',
		views.TransaccionUpdateView.as_view(),
		name='transaccion-edicion'
	),
	re_path(
		r'detalle/transaccion/(?P<id_transaccion>[0-9]+)/',
		views.get_movimientos,
		name='transaccion-detalle'
	),
	re_path(
        r'ajax/transaccion/(?P<id_transaccion>[0-9]+)/',
        views.cuentas,
        name='ajax-transaccion'
    ),
	path(
		'movimientos/',
		views.MovimientosListView.as_view(),
		name='movimientos'
	),
	path(
		'crear/movimiento/',
		views.MovimientoCreateView.as_view(),
		name='movimiento-crear'
	),
	path(
		'edicion/movimiento/<slug:pk>/',
		views.MovimientoUpdateView.as_view(),
		name='movimiento-edicion'
	),
	path(
		'detalle/movimiento/<slug:pk>/',
		views.CuentaDetailView.as_view(),
		name='movimiento-detalle'
	),
	re_path(
		'ajax/cuenta/',
		views.load_sub_cuenta,
		name='ajax-subcuenta'
	),
	path(
		'ajax/transaccion/',
		views.TransaccionCreateView.as_view(),
		name='ajax-transaccion'
	),
	re_path(
        r'ajax/movimiento/(?P<id_movimiento>[0-9]+)/',
        views.cuentas,
        name='ajax-movimiento'
    ),
	re_path(
        r'detalle/perfil/(?P<pk>[0-9]+)/$',
        views.PerfilDetailView.as_view(),
        name='perfil-detalle'
    ),
    re_path(
        r'edicion/perfil/(?P<pk>[0-9]+)/$',
        views.PerfilUpdateView.as_view(),
        name='perfil-edicion'
    ),
    re_path(
        r'ajax/estados_financieros(?P<id_estado_financiero>[0-9]+)/',
        views.estados_financieros,
        name='ajax-estados_financieros'
    ),
]

apps/inventario/urls.py
from django.urls import path, re_path

from . import views

app_name = 'inventario'
urlpatterns = [
	path(
		'import/cliente/',
		views.import_data_cliente,
		name='import-cliente'
	),
	path(
		'import/proveedor/',
		views.import_data_proveedor,
		name='import-proveedor'
	),
	path(
		'import/recursos/',
		views.import_data_recursos,
		name='import-recursos'
	),
	path(
		'import/materias/',
		views.import_data_materia,
		name='import-materias'
	),
	path(
		'import/impuestos/',
		views.import_data_impuesto,
		name='import-impuesto'
	),
	path(
		'proveedores/',
		views.ProveedoresListView.as_view(),
		name='proveedores'
	),
	path(
		'clientes/',
		views.ClientesListView.as_view(),
		name='clientes'
	),
	path(
		'ventas/',
		views.VentasListView.as_view(),
		name='ventas'
	),
	path(
		'compras/',
		views.ComprasListView.as_view(),
		name='compras'
	),
	path(
		'materiales/',
		views.MateriasPrimasListView.as_view(),
		name='materia-prima'
	),
	path(
		'impuestos/',
		views.ImpuestosListView.as_view(),
		name='impuestos'
	),
	re_path(
		r'kardex/(?P<id_kardex>[0-9]+)/',
		views.get_movimientos,
		name='kardex'
	),
	path(
		'crear/proveedor/',
		views.ProveedorCreateView.as_view(),
		name='proveedor-crear'
	),
	path(
		'crear/cliente/',
		views.ClienteCreateView.as_view(),
		name='cliente-crear'
	),
	path(
		'crear/venta/',
		views.VentaCreateView.as_view(),
		name='venta-crear'
	),
	path(
		'crear/compra/',
		views.CompraCreateView.as_view(),
		name='compra-crear'
	),
	path(
		'crear/impuesto/',
		views.ImpuestoCreateView.as_view(),
		name='impuesto-crear'
	),
	path(
		'crear/material/',
		views.MateriaPrimaCreateView.as_view(),
		name='material-crear'
	),
	path(
		'edicion/proveedor/<slug:pk>/',
		views.ProveedorUpdateView.as_view(),
		name='proveedor-edicion'
	),
	path(
		'edicion/cliente/<slug:pk>/',
		views.ClienteUpdateView.as_view(),
		name='cliente-edicion'
	),
	path(
		'edicion/impuesto/<slug:pk>/',
		views.ImpuestoUpdateView.as_view(),
		name='impuesto-edicion'
	),
	path(
		'edicion/material/<slug:pk>/',
		views.MateriaPrimaUpdateView.as_view(),
		name='materia_prima-edicion'
	),
	path(
		'detalle/proveedor/<slug:pk>/',
		views.ProveedorDetailView.as_view(),
		name='proveedor-detalle'
	),
	path(
		'detalle/cliente/<slug:pk>/',
		views.ClienteDetailView.as_view(),
		name='cliente-detalle'
	),
	path(
		'detalle/impuesto/<slug:pk>/',
		views.ImpuestoDetailView.as_view(),
		name='impuesto-detalle'
	),
	path(
		'detalle/material/<slug:pk>/',
		views.MateriaPrimaDetailView.as_view(),
		name='materia-prima-detalle'
	),
	re_path(
		r'detalle/compra/(?P<id_compra>[0-9]+)/',
		views.get_compra,
		name='materia-compra'
	),
	re_path(
        r'ajax/proveedor/(?P<id_proveedor>[0-9]+)/',
        views.proveedores,
        name='ajax-proveedor'
    ),
    re_path(
        r'ajax/cliente/(?P<id_cliente>[0-9]+)/',
        views.clientes,
        name='ajax-cliente'
    ),
    re_path(
        r'ajax/impuesto/(?P<id_impuesto>[0-9]+)/',
        views.impuestos,
        name='ajax-impuesto'
    ),
    re_path(
        r'ajax/materiaprima/(?P<id_materia_prima>[0-9]+)/',
        views.materiales,
        name='ajax-materia-prima'
    ),
	path(
		'ajax/compra/',
		views.CompraCreateView.as_view(),
		name='ajax-compra'
	),
    re_path(
		'ajax/load/materia/',
		views.load_materia,
		name='ajax-materia'
	),
	path(
		'ajax/venta/',
		views.VentaCreateView.as_view(),
		name='ajax-venta'
	),
]

apps/planilla/urls.py
from django.urls import path, re_path

from . import views

app_name = 'planilla' 

urlpatterns = [
    path(
		'import/puestos/',
		views.import_data_puesto,
		name='import-puesto'
	),
    path(
		'import/empleados/',
		views.import_data_empleado,
		name='import-empleado'
	),
    path(
		'import/usuarios/',
		views.import_data_usuario,
		name='import-usuario'
	),
    path(
		'import/departamentos/',
		views.import_data_departamento,
		name='import-departamento'
	),
    path(
        'departamentos/',
        views.DepartamentosListView.as_view(),
        name='departamentos'
    ),
    path(
        'crear/departamento',
        views.DepartamentoCreateView.as_view(),
        name='departamento-crear'
    ),
    path(
        'edicion/departamento/<slug:pk>',
        views.DepartamentoUpdateView.as_view(),
        name='departamento-edicion'
    ),
    path(
        'detalle/departamento/<slug:pk>',
        views.DepartamentoDetailView.as_view(), 
        name='departamento-detalle'
    ),
    re_path(
        r'ajax/departamento/(?P<id_departamento>[0-9]+)/',
        views.departamentos,
        name='ajax-departamento'
    ),
    path(
        'puestos/',
        views.PuestosListView.as_view(),
        name='puestos'
    ),
    path(
        'crear/puesto/',
        views.PuestoCreateView.as_view(),
        name='puesto-crear'
    ),
    path(
        'edicion/puesto/<slug:pk>',
        views.PuestoUpdateView.as_view(),
        name='puesto-edicion'
    ),
    path(
        'detalle/puesto/<slug:pk>',
        views.PuestoDetailView.as_view(),
        name='puesto-detalle'
    ),
    re_path(
        r'ajax/puesto/(?P<id_puesto>[0-9]+)/',
        views.puestos,
        name='ajax-puesto'
    ),
    path(
        'empleados/', 
        views.EmpleadosListView.as_view(),
        name='empleados'
    ),
    path(
        'crear/empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado-crear'
    ),
    path(
        'edicion/empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado-edicion'
    ),
    path(
        'detalle/empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado-detalle'
    ),
    re_path(
        r'ajax/empleado/(?P<id>[0-9]+)/',
        views.empleados,
        name='ajax-empleado'
    ),
] 

templates/header&footer.html
{% extends "base.html" %}
{% block title %}
{% endblock %}

{% block header %}
  <header>
    <nav class="navbar navbar-expand static-top bg-dark">
    <a href="{% url 'contabilidad:index' %}">
        {% load staticfiles %}
      <img class="image-circle" style="max-width:120px; margin-top: -7px;" src="{% static 'media/images/logo.png' %}">
    </a>
    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      {% if user.is_authenticated %}
        <i class="fas fa-bars" style="margin-left: 10%;"></i>
      {% endif %}
    </button>
    {% if user.is_authenticated %}
    <!-- Navbar -->
    <ul class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0 navbar-nav text-white">
      <li class="nav-item dropdown no-arrow bold h5">
        <a class="bold nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #f8f9fa !important">
          {% if user.first_name %}
            <i>{{ user.first_name }} {{ user.last_name }} <span class="fas fa-user-circle fa-fw"></span></i>
          {% else %}
            <i>{{ user.username }} <span class="fas fa-user-circle fa-fw"></span></i>
          {% endif %}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="detalle/perfil/{{user.id}}">Ver Perfil</a>
          <a class="dropdown-item" href="edicion/perfil/{{user.id}}">Modificar Perfil</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Salir</a>
        </div>
      </li>
    </ul>
    {% endif %}
  </nav>
  </header>
{% endblock header%}
{% block content %}
  {% block sidebar %}
  {% endblock sidebar %}
  {% block tables %}
  {% endblock tables %}
{% endblock content %}
{% block footer %}
  <footer class="sticky-footer bg-light fixed" style="background-color: #ecedf1 !important; border-top: 1px solid #d2d6de">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <p class="h6 m-0 text-black bold">Copyright &copy; SAeL 2018 | Sistema Administrativo en Línea - Chalácteos</p>
        </div>
      </div>
  </footer>
{% endblock footer %}

templates/index.html
{% extends 'header&footer.html' %}
{% block title %}SCIeL - Inicio{% endblock title %}

{% block content %}
    
  {% block sidebar %}
  {% endblock sidebar %}
  <div id="content-wrapper">
      <div class="container-fluid col-8 content-center">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            SAeL
          </li>
          <li class="breadcrumb-item active">Menú</li>
        </ol>
        <!-- Icon Cards-->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-balance-scale"></i>
                <strong>Contabilidad General</strong>
            </div>
            <div class="card-body">
                <div class="row bold">
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'contabilidad:cuentas' %}')">
                        <div class="card text-white bg-primary o-hidden h-100">
                            <div class="card-body">
                                <div class="card-body-icon">
                                <i class="fas fa-fw fa-book"></i>
                                </div>
                                <div class="mr-5">Catálogo de Cuentas</div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">Ver Detalles</span>
                                <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'contabilidad:transacciones' %}')">
                        <div class="card text-white bg-warning o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                            <i class="fas fa-fw fa-database"></i>
                            </div>
                            <div class="mr-5">Transacciones</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#">
                            <span class="float-left">Ver Detalles</span>
                            <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'contabilidad:estados-financieros' %}')">
                        <div class="card text-white bg-success o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-edit"></i>
                            </div>
                            <div class="mr-5">Estados Financieros</div>
                        </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">Ver Detalles</span>
                                <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'inventario:impuestos' %}')">
                        <div class="card text-white bg-danger o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-bank"></i>
                            </div>
                            <div class="mr-5">Impuestos</div>
                        </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">Ver Detalles</span>
                                <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-check-circle"></i>
                <strong>Contabilidad de Costos</strong>
            </div>
            <div class="card-body">
                <div class="row bold">
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'inventario:proveedores' %}')">
                        <div class="card text-white bg-primary o-hidden h-100">
                            <div class="card-body">
                                <div class="card-body-icon">
                                <i class="fas fa-fw fa-address-book"></i>
                                </div>
                                <div class="mr-5">Proveedores</div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">Ver Detalles</span>
                                <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'inventario:clientes' %}')">
                        <div class="card text-white bg-warning o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                            <i class="fas fa-fw fa-address-card"></i>
                            </div>
                            <div class="mr-5">Clientes</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#">
                            <span class="float-left">Ver Detalles</span>
                            <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'inventario:ventas' %}')">
                        <div class="card text-white bg-success o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-cart-arrow-down"></i>
                            </div>
                            <div class="mr-5">Ventas</div>
                        </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">Ver Detalles</span>
                                <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'inventario:compras' %}')">
                        <div class="card text-white bg-danger o-hidden h-100">
                            <div class="card-body">
                                <div class="card-body-icon">
                                <i class="fas fa-fw fa-cart-plus"></i>
                                </div>
                                <div class="mr-5">Compras</div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">Ver Detalles</span>
                                <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'inventario:materia-prima' %}')">
                        <div class="card text-white bg-info o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                            <i class="fas fa-fw fa-archive"></i>
                            </div>
                            <div class="mr-5">Materias Primas</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#">
                            <span class="float-left">Ver Detalles</span>
                            <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-check-circle"></i>
                <strong>Recursos Humanos</strong>
            </div>
            <div class="card-body">
                <div class="row bold">
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'planilla:departamentos' %}')">
                        <div class="card text-white bg-primary o-hidden h-100">
                            <div class="card-body">
                                <div class="card-body-icon">
                                <i class="fas fa-fw fa-building"></i>
                                </div>
                                <div class="mr-5">Departamentos</div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">Ver Detalles</span>
                                <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'planilla:puestos' %}')">
                        <div class="card text-white bg-warning o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                            <i class="fas fa-fw fa-industry"></i>
                            </div>
                            <div class="mr-5">Puestos</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#">
                            <span class="float-left">Ver Detalles</span>
                            <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-4" onclick="redirect('{% url 'planilla:empleados' %}')">
                        <div class="card text-white bg-success o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-id-card"></i>
                            </div>
                            <div class="mr-5">Empleados</div>
                        </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">Ver Detalles</span>
                                <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
        <!-- Sticky Footer -->
      </div>
      <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
{% endblock content %}
{% block footer %}
  <footer class="py-5 bg-dark">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <p class="h6 m-0 text-white bold">Copyright &copy; SAeL 2018 | Sistema Administrativo en Línea - Chalácteos</p>
        </div>
      </div>
  </footer>
{% endblock footer %}

templates/sidebarContabilidad.html
<!-- Sidebar -->
{% if user.is_authenticated %}
  <ul class="sidebar bg-dark navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'contabilidad:cuentas' %}">
        <i class="fas fa-fw fa-book"></i>
        <span>Catálogo de Cuentas</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'contabilidad:estados-financieros' %}">
        <i class="fas fa-fw fa-edit"></i>
        <span>Estados Financieros</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'contabilidad:transacciones' %}">
        <i class="fas fa-fw fa-database"></i>
        <span>Transacciones del período</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">
        <i class="fas fa-fw fa-cogs"></i>
        <span>Ajustes</span>
      </a>
    </li>
  </ul>
{% endif %}

templates/sidebarCosteo.html
<!-- Sidebar -->
{% if user.is_authenticated %}
	<ul class="sidebar bg-dark navbar-nav">
	    <li class="nav-item">
	      <a class="nav-link" href=#">
	        <i class="fas fa-fw fa-building"></i>
	        <span>Orden de fabricación</span>
	      </a>
	    </li>
	</ul>
{% endif %}

templates/sidebarEstadosFinancieros.html
<!-- Sidebar -->
{% if user.is_authenticated %}
  <ul class="sidebar bg-dark navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'inventario:proveedores' %}">
        <i class="fas fa-pencil-square-o"></i>
        <span>Balance de Comprobación</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'inventario:clientes' %}">
        <i class="fas fa-fw fa-user"></i>
        <span>Estados de Capital</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'inventario:ventas' %}">
        <i class="fas fa-money"></i>
        <span>Estados de Resultados</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">
        <i class="fas fa-book"></i>
        <span>Balances Generales</span>
      </a>
  </ul>
{% endif %}

templates/sidebarInventario.html
<!-- Sidebar -->
{% if user.is_authenticated %}
  <ul class="sidebar bg-dark navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'inventario:proveedores' %}">
        <i class="fas fa-fw fa-address-book"></i>
        <span>Proveedores</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'inventario:clientes' %}">
        <i class="fas fa-fw fa-address-card"></i>
        <span>Clientes</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'inventario:materia-prima' %}">
        <i class="fas fa-fw fa-list"></i>
        <span>Materia Prima</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'inventario:ventas' %}">
        <i class="fas fa-fw fa-cart-plus"></i>
        <span>Ventas</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'inventario:compras' %}">
        <i class="fas fa-fw fa-shopping-cart"></i>
        <span>Compras</span>
      </a>
    </li>
  </ul>
{% endif %}

templates/sidebarPlanilla.html
<!-- Sidebar -->
{% if user.is_authenticated %}
  <ul class="sidebar bg-dark navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'planilla:departamentos' %}">
        <i class="fas fa-fw fa-building"></i>
        <span>Departamentos</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'planilla:puestos' %}">
        <i class="fas fa-fw fa-industry"></i>
        <span>Puestos</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'planilla:empleados' %}">
        <i class="fas fa-fw fa-id-card"></i>
        <span>Empleados</span>
      </a>
    </li>
  </ul>
{% endif %}