ChalacteosApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.contabilidad.urls', namespace='contabilidad'), name='contabilidad'),
    path('', include('apps.inventario.urls', namespace='inventario'), name='inventario'),
    path('',include('apps.planilla.urls', namespace='planilla'), name='planilla'),
    path('costeo/',include('apps.costeo.urls', namespace='costeo'), name='costeo')
]

apps/planilla/urls.py
from django.urls import path, re_path

from . import views

app_name = 'planilla' 

urlpatterns = [
    path(
		'import/puestos/',
		views.import_data_puesto,
		name='import-puesto'
	),
    path(
		'import/empleados/',
		views.import_data_empleado,
		name='import-empleado'
	),
    path(
		'import/usuarios/',
		views.import_data_usuario,
		name='import-usuario'
	),
    path(
		'import/departamentos/',
		views.import_data_departamento,
		name='import-departamento'
	),
    path(
        'departamentos/',
        views.DepartamentosListView.as_view(),
        name='departamentos'
    ),
    path(
        'crear/departamento',
        views.DepartamentoCreateView.as_view(),
        name='departamento-crear'
    ),
    path(
        'edicion/departamento/<slug:pk>',
        views.DepartamentoUpdateView.as_view(),
        name='departamento-edicion'
    ),
    path(
        'detalle/departamento/<slug:pk>',
        views.DepartamentoDetailView.as_view(), 
        name='departamento-detalle'
    ),
    re_path(
        r'ajax/departamento/(?P<id_departamento>[0-9]+)/',
        views.departamentos,
        name='ajax-departamento'
    ),
    path(
        'puestos/',
        views.PuestosListView.as_view(),
        name='puestos'
    ),
    path(
        'crear/puesto/',
        views.PuestoCreateView.as_view(),
        name='puesto-crear'
    ),
    path(
        'edicion/puesto/<slug:pk>',
        views.PuestoUpdateView.as_view(),
        name='puesto-edicion'
    ),
    path(
        'detalle/puesto/<slug:pk>',
        views.PuestoDetailView.as_view(),
        name='puesto-detalle'
    ),
    re_path(
        r'ajax/puesto/(?P<id_puesto>[0-9]+)/',
        views.puestos,
        name='ajax-puesto'
    ),
    path(
        'empleados/', 
        views.EmpleadosListView.as_view(),
        name='empleados'
    ),
    path(
        'crear/empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado-crear'
    ),
    path(
        'edicion/empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado-edicion'
    ),
    path(
        'detalle/empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado-detalle'
    ),
    re_path(
        r'ajax/empleado/(?P<id>[0-9]+)/',
        views.empleados,
        name='ajax-empleado'
    ),
] 

apps/planilla/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from apps.contabilidad.models import Empresa


class Departamento(models.Model):
	id_departamento = models.AutoField(
		primary_key=True
	)
	empresa = models.ForeignKey(
		Empresa,
		verbose_name='Empresa',
		on_delete=models.DO_NOTHING,
		blank=False,
		default=0,
		null=False
	)
	nombre = models.CharField(
		verbose_name='Nombre del Departamento',
		max_length=40,
		null=False, 
		blank=False,
		help_text='Ingrese el nombre del departamento'
	)
	descripcion = models.TextField(
		verbose_name='Descripcion del Departamento',
		max_length=250,
		null=True, 
		blank=True,
		help_text='Ingrese una descripcion del departamento'
	)

	class Meta:
		verbose_name = 'Departamento'
		verbose_name_plural = 'Departamentos'
		unique_together = ("id_departamento", "nombre")
		ordering= ["id_departamento"]

	def __str__(self):
		return '%s' % (self.nombre)

class Puesto(models.Model):
	id_puesto = models.AutoField(
		primary_key=True
	)
	departamento = models.ForeignKey(
		Departamento,
		verbose_name='Departamento',
		on_delete=models.DO_NOTHING,
		blank=False,
		default=0,
		null=False,
		help_text='Seleccione el departamento'
	)
	codigo_puesto = models.CharField(
		verbose_name='Codigo del puesto',
		max_length=50,
		null=False,
		help_text='Ingrese el codigo del puesto',
		blank=False
	)
	nombre_funcional = models.CharField(
		verbose_name='Nombre del Puesto',
		max_length=50, 
		null=False, 
		blank=False,
		help_text='Ingrese el nombre del puesto'
	)
	descripcion = models.TextField(
		verbose_name='Descripcion del Puesto',
		max_length=50, 
		help_text='Ingrese una descripcion del puesto'
	)
	salario_base = models.DecimalField(
		verbose_name='Salario de un Puesto',
		max_digits=6, 
		decimal_places=2, 
		null=False, 
		blank=False,
		validators=[
			MinValueValidator(
				0, 
				message='Este campo debe ser positivo'
			)
		],
		help_text='Ingrese el salario para este puesto'
	)

	class Meta:
		verbose_name = 'Puesto'
		verbose_name_plural = 'Puestos'
		unique_together = ("codigo_puesto", "nombre_funcional")
		ordering= ["id_puesto"]
 

	def __str__(self):
		return ' %s' % (self.nombre_funcional)


class Empleado(models.Model):
	empleado = models.OneToOneField(
		User,
		on_delete=models.CASCADE
	)
	puesto = models.ForeignKey(
		Puesto,
		verbose_name='Puesto',
		on_delete=models.DO_NOTHING,
		blank=False,
		null=True
	)
	dui = models.CharField(
		verbose_name='DUI',
		max_length=10, 
		null=True, 
		blank=False,
		help_text='Ingrese el Documento Único de Identidad del empleado' 
	)
	fecha_nacimiento = models.DateField(
		verbose_name='Fecha de nacimiento',
		null=True, 
		blank=False,
		help_text='Ingrese el segundo apellido de la persona' 
	)
	telefono = models.IntegerField(
		verbose_name='Numero de telefono',
		null=True, 
		blank=False,
		help_text='Ingrese el telefono'
	)
	direccion = models.CharField(
		verbose_name='Direccion',
		max_length=50,
		help_text='Ingrese la direccion',
		null=True
	)
	is_active = models.BooleanField(
		verbose_name='¿El empleado está de alta?',
		default=True,
		help_text='Active esta casilla para mantener de alta al empleado'
	)

	class Meta:
		verbose_name = 'Empleado'
		verbose_name_plural = 'Empleados'
		ordering= ["puesto", 'dui']

	def __str__(self):
		return '%s %s' % (self.empleado.first_name, self.empleado.last_name)

	@receiver(post_save, sender=User)
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			Empleado.objects.create(empleado=instance)

	@receiver(post_save, sender=User)
	def save_user_profile(sender, instance, **kwargs):
		instance.empleado.save()

apps/planilla/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email'
        ]

class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = Empleado
        fields = [
            'puesto',
            'dui',
            'fecha_nacimiento',
            'telefono',
            'direccion',
            'is_active',
        ]

class DepartamentoForm(forms.ModelForm):
    scope_prefix = 'departamento_data'
    form_name = 'departamento_form'
    class Meta:
        model = Departamento
        fields = [
            'nombre'
        ]
    def __init__(self, *args, **kwargs):
        super(DetalleCompraForm, self).__init__(*args,**kwargs)
        self.fields['nombre'].choices = (('', '---------'),)
        self.fields['nombre'].widget.attrs.update({'disabled': 'true'})

class EmpleadoBoletaForm(forms.ModelForm):
    scope_prefix = 'empleado_data'
    form_name = 'empleado_form'
    class Meta:
        model = Empleado
        fields = [
            'puesto',
            'dui',
            'fecha_nacimiento',
            'telefono',
            'direccion',
            'is_active',
        ]

class EmpresaForm(forms.ModelForm):
    scope_prefix = 'empresa_data'
    form_name = 'empresa_form'
    class Meta:
        model = Empresa
        fields = [
            'nombre'
        ]

apps/planilla/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView, View
from django.views.generic.edit import FormView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.forms.models import model_to_dict
from django.template import loader
from django.urls import reverse_lazy, reverse
from django.http.response import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from .models import *
from .forms import *
from apps.contabilidad import views as conta

import json
import csv
import datetime


class DepartamentosListView(ListView, LoginRequiredMixin):
	model = Departamento
	template_name = 'planilla/gestionarDepartamentos.html'
	context_object_name = 'departamentos'


class PuestosListView(ListView, LoginRequiredMixin):
	model = Puesto
	template_name = 'planilla/gestionarPuestos.html'
	context_object_name = 'puestos'


class EmpleadosListView(ListView, LoginRequiredMixin):
	model = Empleado
	template_name = 'planilla/gestionarEmpleados.html'
	context_object_name = 'empleados'

	def get_queryset(self):
		context = Empleado.objects.all().filter(is_active = True)
		if context:
			return context
		else:
			return render(self.request, template_name = '404.html')


class DepartamentoCreateView(CreateView, LoginRequiredMixin):
	model = Departamento
	template_name = 'editForm.html'
	success_url = reverse_lazy('planilla:departamentos')
	fields = [
		'nombre',
		'descripcion',
	]


class PuestoCreateView(CreateView, LoginRequiredMixin):
	model = Puesto
	template_name = 'editForm.html'
	success_url = reverse_lazy('planilla:puestos')
	fields = [
		'departamento',
		'codigo_puesto',
		'nombre_funcional',
		'descripcion',
		'salario_base'
	]


class EmpleadoCreateView(View, LoginRequiredMixin):
	
	def get(self, request):
		user_form = UserForm(instance = request.user)
		empleado_form = EmpleadoForm(instance = request.user.empleado)
		return render(
			request,
			'planilla/editEmpleado.html',
			context = {
				'user_form': user_form,
				'empleado_form': empleado_form
			}
		)
	
	def post(self, request):
		user_form = UserForm(request.POST, instance = request.user)
		empleado_form = EmpleadoForm(request.POST, instance = request.user.empleado)
		if user_form.is_valid() and empleado_form.is_valid():
			user_form.save()
			empleado_form.save()
			messages.success(request, 'El empleado fue modificado exitosamente')
			return redirect('planilla:empleados')
		messages.error(request, 'Por favor corrija los siguientes errores')


class DepartamentoUpdateView(UpdateView, LoginRequiredMixin):
	model = Departamento
	template_name = 'editForm.html'
	success_url = reverse_lazy('planilla:departamentos')
	fields = [
		'nombre',
		'descripcion',
	]


class PuestoUpdateView(UpdateView, LoginRequiredMixin):
	model = Puesto
	template_name = 'editForm.html'
	success_url = reverse_lazy('planilla:puestos')
	fields = [
		'departamento',
		'codigo_puesto',
		'nombre_funcional',
		'descripcion',
		'salario_base'
	]


class EmpleadoUpdateView(UpdateView, LoginRequiredMixin):
	model = Empleado
	template_name = 'editForm.html'
	success_url = reverse_lazy('planilla:empleados')
	fields = [
		'puesto',
		'dui',
		'fecha_nacimiento',
		'telefono',
		'direccion',
		'is_active',
	]


class DepartamentoDetailView(DetailView, LoginRequiredMixin):
	model = Departamento
	template_name = 'planilla/viewDepartamento.html'
	success_url = reverse_lazy('planilla:departamentos')
	fields = [
		'nombre',
		'descripcion',
	]
	context_object_name = 'departamento'


class PuestoDetailView(DetailView, LoginRequiredMixin):
	model = Puesto
	template_name = 'planilla/viewPuesto.html'
	success_url = reverse_lazy('planilla:puestos')
	fields = [
		'departamento',
		'codigo_puesto',
		'nombre_funcional',
		'descripcion',
		'salario_base'
	]
	context_object_name = 'puesto'


class EmpleadoDetailView(DetailView, LoginRequiredMixin):
	model = Empleado
	template_name = 'planilla/viewEmpleado.html'
	success_url = reverse_lazy('planilla:empleados')
	fields = [
		'puesto',
		'dui',
		'user',
		'fecha_nacimiento',
		'telefono',
		'direccion',
		'is_active',
	]
	context_object_name = 'empleado'

@login_required(login_url = '/sign-in/')
def departamentos(request, id_departamento):   
	if request.method == 'DELETE':
		parametro = Departamento.objects.get(id_departamento = id_departamento)
		parametro.delete()
		message = "El departamento fue borrado exitosamente"
		return JsonResponse(data = {'message': message})

@login_required(login_url = '/sign-in/')
def puestos(request, id_puesto):   
	if request.method == 'DELETE':
		parametro = Puesto.objects.get(id_puesto = id_puesto)
		parametro.delete()
		message = "El puesto fue borrado exitosamente"
		return JsonResponse(data = {'message': message})

@login_required(login_url = '/sign-in/')
def empleados(request, id):   
	if request.method == 'DELETE':
		parametro = Empleado.objects.get(id=id)
		parametro.is_active = False
		message = "El empleado fue borrado exitosamente"
		return JsonResponse(data={'message': message})

def import_data_departamento(request):
	f = 'C:\\departamentos.csv'
	with open(f) as file:
		reader = csv.reader(file)
		for new in reader:
			row = new[0].split(";")
			empresa = Empresa.objects.get(id_empresa=new[1])
			nombre = new[2]
			descripcion = new[3]
			objeto, created = Departamento.objects.update_or_create(
				empresa = empresa,
				nombre = nombre,
				descripcion = descripcion
			)
	return HttpResponse('Hecho')

@login_required(login_url = '/sign-in/')
def import_data_puesto(request):
	f = 'C:\\puestos.csv'
	with open(f) as file:
		reader = csv.reader(file)
		for new in reader:
			row = new[0].split(";")
			departamento = Departamento.objects.get(id_departamento=new[1])
			codigo_puesto = new[2]
			nombre_funcional = new[3]
			descripcion = new[4]
			salario_base = float(new[8])
			objeto, created = Puesto.objects.update_or_create(
				departamento = departamento,
				codigo_puesto = codigo_puesto,
				nombre_funcional = nombre_funcional,
				descripcion = descripcion,
				salario_base = salario_base,
			)
	return HttpResponse('Hecho')
 
@login_required(login_url = '/sign-in/')
def import_data_empleado(request):
	f = 'C:\\empleados.csv'
	with open(f) as file:
		count = 2
		reader = csv.reader(file)
		for new in reader:
			row = new[0].split(";")
			empleado = User.objects.get(id=count)
			puesto = Puesto.objects.get(id_puesto=new[0])
			dui = new[1]
			fecha_nacimiento = datetime.datetime.strptime(new[2], '%d/%m/%Y')
			telefono = new[3]
			direccion = new[4]
			objeto, created = Empleado.objects.update_or_create(
				empleado=empleado,
				puesto=puesto,
				dui=dui,
				fecha_nacimiento = fecha_nacimiento,
				telefono = telefono,
				direccion = direccion,
				is_active = True,
			)
			count+=1
	return HttpResponse('Hecho') 

@login_required(login_url = '/sign-in/')
def import_data_usuario(request):
	f = 'C:\\usuarios.csv'
	with open(f) as file:
		reader = csv.reader(file)
		for new in reader:
			row = new[0].split(";")
			nombres = new[0]
			apellidos = new[1]
			correo = new[2]
			objeto, created = User.objects.update_or_create(
				username=new[0].split(";")[0],
				first_name = nombres,
				last_name = apellidos,
				email = correo
			)
	return HttpResponse('Hecho') 

templates/planilla/editEmpleado.html
{% extends 'header&footer.html' %}
{% block title %}SCIeL - Edición {% endblock title %}

{% block content %}
  
  {% block sidebar %}
    {% include 'sidebarPlanilla.html' %}
  {% endblock sidebar %}
  {% block tables %}
  {% load bootstrap %}
    <div id="content-wrapper">
      <div class="container-fluid">
      <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Edición  | Creación</a>
          </li>
          <li class="breadcrumb-item active">Ingreso de Datos</li>
        </ol>
        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header text-center">
            <i class="fas fa-edit"></i>
            Edición | Creación
            <i class="fas fa-plus-circle"></i>
          </div>
          <div class="card-body">
            <form action="" method="POST" disabled id="detalleForm">
                {% csrf_token %}
                {{ user_form|bootstrap_inline }}
                {{ empleado_form|bootstrap_inline }}
                <div class="form-group text-center">
                    <button id='aprobar' type="submit" class='btn btn-primary' style="width: 30%" href='#'>Guardar</button>
                    <button class='btn btn-secondary' onclick="javascript:history.back()" style="width: 30%" type='button'>Cancelar</button>                    
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endblock tables %}
{% endblock content %}

templates/planilla/gestionarDepartamentos.html
{% extends 'header&footer.html' %}
{% block title %}SAeL - Gestión de Departamentos{% endblock title %}

{% block content %}    
  {% block sidebar %}
    {% include 'sidebarPlanilla.html' %}
  {% endblock sidebar %}
  {% block tables %}
    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Planilla</a>
          </li>
          <li class="breadcrumb-item active">Departamentos</li>
        </ol>
        <!-- DataTables Example -->
        <div class="alert bold alert-info">
          <i class="fas fw fa-plus-circle"></i>
          <a href="{% url 'planilla:departamento-crear' %}">
            <strong>¡Click Aquí para agregar un nuevo departamento!</strong>
          </a>
        </div>
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Lista de Departamentos
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                      <th>#</th>
                      <th>Nombre</th>
                      <th>Descripcion</th>
                      <th>Operaciones</th>
                  </tr>
                </thead>
                <tbody>
                    {% for departamento in departamentos %}
                        <tr id="{{departamento.id_departamento}}">
                            <td class="text-center">{{departamento.id_departamento}}</td>
                            <td>{{ departamento.nombre }}</td>
                            <td>{{ departamento.descripcion }}</td>
                            <td class="text-center">
                                <a class="fas fa-w fa-eye" name="ver" href="#"  data-toggle="modal" onclick="redirectView('DEPARTAMENTO', {{ departamento.id_departamento }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa-edit" name="editar" href="#" onclick="redirectEdit('DEPARTAMENTO', {{ departamento.id_departamento }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa fa-trash" name="eliminar" href="#" onclick="operacion({{ departamento.id_departamento }}, '{{departamento.nombre}}', 'DEPARTAMENTO');" style="color:gray !important"></a>
                            </td>                          
                        </tr>
                    {% empty %}
                      <div class="alert bold alert-danger text-center">
                        <i class="fas fw fa-question-circle">
                          <strong>¡Opps! Parece que no tienes ningun departamento registrado.</strong>
                        </i><br><hr>
                        <i class="fas fw fa-plus-circle"></i>
                        <a href="{% url 'planilla:puesto-crear' %}">
                          <strong>¡Click Aquí para agregar un nuevo departamento!</strong>
                        </a>
                      </div>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  {% endblock tables %}
    
{% endblock content %}

templates/planilla/gestionarEmpleados.html
{% extends 'header&footer.html' %}
{% block title %}SAeL - Gestión de Empleados{% endblock title %}

{% block content %}    
  {% block sidebar %}
    {% include 'sidebarPlanilla.html' %}
  {% endblock sidebar %}
  {% block tables %}
    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Planilla</a>
          </li>
          <li class="breadcrumb-item active">Empleados</li>
        </ol>
        <!-- DataTables Example -->
        <div class="alert bold alert-info">
          <i class="fas fw fa-plus-circle"></i>
          <a href="{% url 'planilla:empleado-crear' %}">
            <strong>¡Click Aquí para agregar un nuevo empleadp!</strong>
          </a>
        </div>
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Lista de Empleados
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                      <th>#</th>
                      <th>Departamento</th>
                      <th>Cargo</th>
                      <th>DUI</th>
                      <th>Apellidos</th>
                      <th>Nombres</th>
                      <th>Fecha de Contrato</th>
                      <th>Operaciones</th>
                  </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                        <tr id="{{empleado.id}}">
                            <td class="text-center">{{empleado.id}}</td>
                            <td>{{ empleado.puesto.departamento }}</td>
                            <td>{{ empleado.puesto }}</td>
                            <td>{{ empleado.dui }}</td>
                            <td>{{ empleado.empleado.last_name }}</td>
                            <td>{{ empleado.empleado.first_name }}</td>
                            <td>{{ empleado.empleado.date_joined }}</td>
                            <td class="text-center">
                                <a class="fas fa-w fa-eye" name="ver" href="#"  data-toggle="modal" onclick="redirectView('EMPLEADO', {{ empleado.id }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa-edit" name="editar" href="#" onclick="redirectEdit('EMPLEADO', {{ empleado.id }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa fa-trash" name="eliminar" href="#" onclick="operacion({{ empleado.id }}, '{{empleado.nombre}}', 'EMPLEADO');" style="color:gray !important"></a>
                            </td>                          
                        </tr>
                    {% empty %}
                      <div class="alert bold alert-danger text-center">
                        <i class="fas fw fa-question-circle">
                          <strong>¡Opps! Parece que no tienes ningun empleado registrado.</strong>
                        </i><br><hr>
                        <i class="fas fw fa-plus-circle"></i>
                        <a href="{% url 'planilla:puesto-crear' %}">
                          <strong>¡Click Aquí para agregar un nuevo empleado!</strong>
                        </a>
                      </div>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  {% endblock tables %}
    
{% endblock content %}

templates/planilla/gestionarPuestos.html
{% extends 'header&footer.html' %}
{% block title %}SAeL - Gestión de Cuentas{% endblock title %}

{% block content %}    
  {% block sidebar %}
    {% include 'sidebarPlanilla.html' %}
  {% endblock sidebar %}
  {% block tables %}
    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Planilla</a>
          </li>
          <li class="breadcrumb-item active">Puestos</li>
        </ol>
        <!-- DataTables Example -->
        <div class="alert bold alert-info">
          <i class="fas fw fa-plus-circle"></i>
          <a href="{% url 'planilla:puesto-crear' %}">
            <strong>¡Click Aquí para agregar un nuevo puesto!</strong>
          </a>
        </div>
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Lista de Puestos
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                      <th>#</th>
                      <th>Codigo</th>
                      <th>Departamento</th>
                      <th>Nombre</th>
                      <th>Descripcion</th>
                      <th>Salario</th>
                      <th>Operaciones</th>
                  </tr>
                </thead>
                <tbody>
                    {% for puesto in puestos %}
                        <tr id="{{puesto.id_puesto}}">
                            <td class="text-center">{{puesto.id_puesto}}</td>
                            <td>{{ puesto.codigo_puesto }}</td>
                            <td>
                              {% ifnotequal puesto.departamento None %}
                                {{ puesto.departamento }}
                              {% endifnotequal %}
                            </td>
                            <td>{{ puesto.nombre_funcional}}</td>
                            <td>{{ puesto.descripcion }}</td>
                            <td>{{ puesto.salario_base }}</td>
                            <td class="text-center">
                                <a class="fas fa-w fa-eye" name="ver" href="#"  data-toggle="modal" onclick="redirectView('PUESTO', {{ puesto.id_puesto }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa-edit" name="editar" href="#" onclick="redirectEdit('PUESTO', {{ puesto.id_puesto }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa fa-trash" name="eliminar" href="#" onclick="operacion({{ puesto.id_puesto }}, '{{puesto.nombre}}', 'PUESTO');" style="color:gray !important"></a>
                            </td>                          
                        </tr>
                    {% empty %}
                      <div class="alert bold alert-danger text-center">
                        <i class="fas fw fa-question-circle">
                          <strong>¡Opps! Parece que no tienes ningun puesto registrado.</strong>
                        </i><br><hr>
                        <i class="fas fw fa-plus-circle"></i>
                        <a href="{% url 'planilla:puesto-crear' %}">
                          <strong>¡Click Aquí para agregar un nuevo puesto!</strong>
                        </a>
                      </div>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  {% endblock tables %}
    
{% endblock content %}