ChalacteosApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.contabilidad.urls', namespace='contabilidad'), name='contabilidad'),
    path('', include('apps.inventario.urls', namespace='inventario'), name='inventario'),
    path('',include('apps.planilla.urls', namespace='planilla'), name='planilla'),
    path('costeo/',include('apps.costeo.urls', namespace='costeo'), name='costeo')
]

apps/inventario/urls.py
from django.urls import path, re_path

from . import views

app_name = 'inventario'
urlpatterns = [
	path(
		'import/cliente/',
		views.import_data_cliente,
		name='import-cliente'
	),
	path(
		'import/proveedor/',
		views.import_data_proveedor,
		name='import-proveedor'
	),
	path(
		'import/recursos/',
		views.import_data_recursos,
		name='import-recursos'
	),
	path(
		'import/materias/',
		views.import_data_materia,
		name='import-materias'
	),
	path(
		'import/impuestos/',
		views.import_data_impuesto,
		name='import-impuesto'
	),
	path(
		'proveedores/',
		views.ProveedoresListView.as_view(),
		name='proveedores'
	),
	path(
		'clientes/',
		views.ClientesListView.as_view(),
		name='clientes'
	),
	path(
		'ventas/',
		views.VentasListView.as_view(),
		name='ventas'
	),
	path(
		'compras/',
		views.ComprasListView.as_view(),
		name='compras'
	),
	path(
		'materiales/',
		views.MateriasPrimasListView.as_view(),
		name='materia-prima'
	),
	path(
		'impuestos/',
		views.ImpuestosListView.as_view(),
		name='impuestos'
	),
	re_path(
		r'kardex/(?P<id_kardex>[0-9]+)/',
		views.get_movimientos,
		name='kardex'
	),
	path(
		'crear/proveedor/',
		views.ProveedorCreateView.as_view(),
		name='proveedor-crear'
	),
	path(
		'crear/cliente/',
		views.ClienteCreateView.as_view(),
		name='cliente-crear'
	),
	path(
		'crear/venta/',
		views.VentaCreateView.as_view(),
		name='venta-crear'
	),
	path(
		'crear/compra/',
		views.CompraCreateView.as_view(),
		name='compra-crear'
	),
	path(
		'crear/impuesto/',
		views.ImpuestoCreateView.as_view(),
		name='impuesto-crear'
	),
	path(
		'crear/material/',
		views.MateriaPrimaCreateView.as_view(),
		name='material-crear'
	),
	path(
		'edicion/proveedor/<slug:pk>/',
		views.ProveedorUpdateView.as_view(),
		name='proveedor-edicion'
	),
	path(
		'edicion/cliente/<slug:pk>/',
		views.ClienteUpdateView.as_view(),
		name='cliente-edicion'
	),
	path(
		'edicion/impuesto/<slug:pk>/',
		views.ImpuestoUpdateView.as_view(),
		name='impuesto-edicion'
	),
	path(
		'edicion/material/<slug:pk>/',
		views.MateriaPrimaUpdateView.as_view(),
		name='materia_prima-edicion'
	),
	path(
		'detalle/proveedor/<slug:pk>/',
		views.ProveedorDetailView.as_view(),
		name='proveedor-detalle'
	),
	path(
		'detalle/cliente/<slug:pk>/',
		views.ClienteDetailView.as_view(),
		name='cliente-detalle'
	),
	path(
		'detalle/impuesto/<slug:pk>/',
		views.ImpuestoDetailView.as_view(),
		name='impuesto-detalle'
	),
	path(
		'detalle/material/<slug:pk>/',
		views.MateriaPrimaDetailView.as_view(),
		name='materia-prima-detalle'
	),
	re_path(
		r'detalle/compra/(?P<id_compra>[0-9]+)/',
		views.get_compra,
		name='materia-compra'
	),
	re_path(
        r'ajax/proveedor/(?P<id_proveedor>[0-9]+)/',
        views.proveedores,
        name='ajax-proveedor'
    ),
    re_path(
        r'ajax/cliente/(?P<id_cliente>[0-9]+)/',
        views.clientes,
        name='ajax-cliente'
    ),
    re_path(
        r'ajax/impuesto/(?P<id_impuesto>[0-9]+)/',
        views.impuestos,
        name='ajax-impuesto'
    ),
    re_path(
        r'ajax/materiaprima/(?P<id_materia_prima>[0-9]+)/',
        views.materiales,
        name='ajax-materia-prima'
    ),
	path(
		'ajax/compra/',
		views.CompraCreateView.as_view(),
		name='ajax-compra'
	),
    re_path(
		'ajax/load/materia/',
		views.load_materia,
		name='ajax-materia'
	),
	path(
		'ajax/venta/',
		views.VentaCreateView.as_view(),
		name='ajax-venta'
	),
]

apps/inventario/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

from apps.contabilidad import models as conta


class Recurso(models.Model):
    id_recurso = models.AutoField(
        primary_key=True
    )
    nombre_recurso = models.CharField(
        verbose_name='Nombre del recurso',
        blank=False,
        max_length=50,
        help_text="Nombre del recurso, sea este materia prima o producto"
    )
    descripcion_recurso = models.CharField(
        verbose_name='Descripción del recurso',
        blank=False,
        max_length=250,
        help_text="Una breve descripción del recurso"
    )
    unidad_medida = models.CharField(
        verbose_name='Unidad de medida',
        blank=False,
        default=None,
        max_length=50,
        null=True,
        help_text="Unidad de medida del recurso. Por ejemplo: libras, litros etc."
    )

    def __str__(self):
        return self.nombre_recurso

    class Meta:
        verbose_name = 'Recurso'
        verbose_name_plural = 'Recursos'
        ordering = ['nombre_recurso']


class Kardex(models.Model):
    id_kardex = models.AutoField(
        primary_key=True
    )
    id_recurso = models.OneToOneField(
        Recurso,
        verbose_name='Recurso',
        on_delete=models.DO_NOTHING,
        blank=False,
        help_text='Seleccion el recurso del que esta compuesto el kardex'
    )

    def __str__(self):
        return str(self.id_recurso)

    class Meta:
        verbose_name = 'Kardex'
        verbose_name_plural = 'Kardexs'
        ordering = ['id_recurso']


class Movimiento(models.Model):
    id_movimiento = models.AutoField(
        primary_key=True
    )
    id_kardex = models.ForeignKey(
        Kardex,
        verbose_name='Kardex',
        on_delete=models.DO_NOTHING,
        blank=False,
        help_text='Seleccion el kardex que posee el movimiento'
    )
    fecha_movimiento = models.DateTimeField(
        verbose_name='Fecha',
        auto_now=True,
        blank=False,
        help_text='Ingrese en que se realizo fecha del movimiento'
    )
    cantidad_movimiento = models.DecimalField(
        verbose_name='Cantidad',
        max_digits=1000,
        decimal_places=2,
        blank=False,
        validators=[
            MinValueValidator(
                0, 
                message="Este campo debe ser positivo"
            )
        ],
        help_text="Ingrese la cantidad actual del producto o materia prima"
    )
    costo_unitario_movimiento = models.DecimalField(
        verbose_name='Costo Unitario',
        max_digits=1000,
        decimal_places=2,
        blank=False,
        validators=[
            MinValueValidator(
                0, 
                message="Este campo debe ser positivo"
            )
        ],
        help_text="Ingrese el costo unitario del producto o materia prima"
    )
    monto_movimiento = models.DecimalField(
        verbose_name='Monto',
        max_digits=1000,
        decimal_places=2,
        blank=False,
        validators=[
            MinValueValidator(
                0, 
                message="Este campo debe ser positivo"
            )
        ],
        help_text="Este campo es auto generado"
    )
    is_Input = models.BooleanField(
        verbose_name='¿Es una entrada?',
        blank=False,
        default=True,
        help_text="Defina si esta transacción es una entrada o salida de materia prima o producto"
    )
    cantidad_saldo = models.DecimalField(
        verbose_name='Cantidad',
        max_digits=1000,
        decimal_places=2,
        blank=False,
        validators=[
            MinValueValidator(
                0, 
                message="Este campo debe ser positivo"
            )
        ],
        help_text="Ingrese la cantidad actual del producto o materia prima",
        null=True
    )
    costo_unitario_saldo = models.DecimalField(
        verbose_name='Costo Unitario',
        max_digits=1000,
        decimal_places=2,
        blank=False,
        validators=[
            MinValueValidator(
                0, 
                message="Este campo debe ser positivo"
            )
        ],
        help_text="Ingrese el costo unitario del producto o materia prima",
        null=True
    )
    monto_saldo = models.DecimalField(
        verbose_name='Monto',
        max_digits=1000,
        decimal_places=2,
        blank=False,
        validators=[
            MinValueValidator(
                0, 
                message="Este campo debe ser positivo"
            )
        ],
        help_text="Este campo es auto generado",
        null=True
    )

    def transaction_date(self):
        self.fecha_movimiento = timezone.now()
        self.save()

    def __str__(self):
        return str(self.fecha_movimiento)


    class Meta:
        verbose_name = 'Movimiento'
        verbose_name_plural = 'Movimientos'
        get_latest_by = 'fecha_movimiento'
        ordering = ['-fecha_movimiento']


class Producto(models.Model):
    id_producto = models.AutoField(
        primary_key=True
    )
    id_recurso = models.OneToOneField(
        Recurso,
        verbose_name='Recurso',
        on_delete=models.CASCADE,
        blank=False,
        help_text='Seleccione el recurso del producto'
    )
    
    def __str__(self):
        return str(self.id_recurso)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id_producto', 'id_recurso']


class Cliente(models.Model):
    id_cliente = models.AutoField(
        primary_key=True
    )
    nombre_cliente = models.CharField(
        verbose_name='Cliente',
        blank=False,
        max_length=50,
        help_text="Nombre del cliente",
    )
    nombre_titular_cliente = models.CharField(
        verbose_name='Titular',
        blank=False,
        max_length=50,
        help_text='Nombre del titular del cliente'
    )

    def __str__(self):
        return self.nombre_cliente

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['nombre_titular_cliente', 'nombre_cliente']


class Proveedor(models.Model):
    id_proveedor = models.AutoField(
        primary_key=True
    )
    nombre_proveedor = models.CharField(
        verbose_name='Proveedor',
        blank=False,
        max_length=50,
        help_text="Nombre del proveedor",
    )
    nombre_titular_proveedor = models.CharField(
        verbose_name='Titular',
        blank=False,
        max_length=50,
        help_text='Nombre del titular del proveedor'
    )

    def __str__(self):
        return self.nombre_proveedor

    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'
        ordering = ['nombre_titular_proveedor', 'nombre_proveedor']


class MateriaPrima(models.Model):
    id_materia_prima = models.AutoField(
        primary_key=True
    )
    id_recurso = models.ForeignKey(
        Recurso,
        verbose_name='Recurso',
        on_delete=models.DO_NOTHING,
        blank=False,
        help_text='Seleccion el recurso para la kardex',
    )
    id_proveedor = models.ForeignKey(
        Proveedor,
        verbose_name='Proveedor',
        on_delete=models.DO_NOTHING,
        blank=False,
        help_text='Seleccion el proveedor al que le pertenece la compra'
    )

    def __str__(self):
        return str(self.id_recurso)

    class Meta:
        verbose_name = 'Materia Prima'
        verbose_name_plural = 'Materias Primas'
        ordering = ['id_proveedor', 'id_recurso']


class Factura(models.Model):
    id_factura = models.AutoField(
        primary_key=True
    )
    sub_total_factura = models.DecimalField(
        verbose_name='Sub Total',
        max_digits=1000,
        decimal_places=2,
        blank=False,
        validators=[
            MinValueValidator(
                0, 
                message="Este campo debe ser positivo"
            )
        ],
        help_text="Ingrese el sub total antes de impuestos"
    )
    total_factura = models.DecimalField(
        verbose_name='Total',
        max_digits=1000,
        decimal_places=2,
        blank=False,
        validators=[
            MinValueValidator(
                0, 
                message="Este campo debe ser positivo"
            )
        ],
        help_text="Ingrese el total (impuestos incluídos)"
    )
    estado_factura = models.CharField(
        verbose_name='Estado de la Factura',
        max_length=20,
        help_text="Estado de la fatura: Despachada, Pendiente de pago, Pendiente de entrada, Entregada"
    )
    monto_aplicacion = models.DecimalField(
        verbose_name='Monto Aplicado',
        max_digits=1000,
        decimal_places=2,
        blank=False,
        validators=[
            MinValueValidator(
                0, 
                message="Este campo debe ser positivo"
            )
        ],
        help_text="Ingrese el recargo por el impuesto a la compra o venta"
    )
    is_credito = models.BooleanField(
        verbose_name='¿La compra es al crédito?',
        default=False,
        help_text='Indique si está factura será pagada al crédito ya sea total o parcialmente'
    )
    is_contado = models.BooleanField(
        verbose_name='¿La compra es al contado?',
        default=False,
        help_text='Indique si está factura será pagada al contado ya sea total o parcialmente'
    )
    proporcion = models.DecimalField(
        verbose_name='proporcion de compra al credito',
        decimal_places=2,
        max_digits=5,
        null=True,
        validators=[
            MinValueValidator(
                0, 
                message='Este campo debe ser positivo'
            ),
            MaxValueValidator(
                100, 
                message='La proporcion debe ser menor 100'
            )
        ]
    )
    transaccion = models.OneToOneField(
        conta.Transaccion,

templates/inventario/chainedVentaForm.html
{% extends 'header&footer.html' %}
{% block title %}SCIeL - Edición / {% endblock title %}

{% block content %}
  
  {% block sidebar %}
    {% include 'sidebarInventario.html' %}
  {% endblock sidebar %}
  {% block tables %}
  {% load bootstrap %}
  {% load l10n %}
    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Edición  | Creación</a>
          </li>
          <li class="breadcrumb-item active">Ingreso de Datos</li>
        </ol>
        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-edit"></i>
                Edición | Creación
            <i class="fas fa-plus-circle"></i>
          </div>
          <div class="card-body" id="1">
            <div>
              <div class="col-lg-12 col-xs-12 border rounded">
                <form name="venta_form" novalidate>
                {% csrf_token %}
                  <div class="row">
                    <div class="col-lg-6 col-xs-12">
                      <h4 class="mb-3 text-center header_id">VENTA</h4>
                      {{ venta_form|bootstrap_inline }}
                    </div>
                    <br>
                    <div  class="col-lg-6 col-xs-12">
                      <h4 class="mb-3 text-center header_id">PRODUCTO</h4>
                      {{ producto_form|bootstrap_inline }}
                      {{ detalle_venta_form|bootstrap_inline }}
                      {{ movimiento_form|bootstrap_inline }}
                    </div>
                  </div>
                  <div class="col-12 text-center">    
                    <button class="btn btn-outline-primary btn-plus" onclick="getData()" type="button">
                      Registrar venta
                      <i class="fas fa-plus-circle"></i>
                    </button>
                  </div><br>
                </form>
              </div>
            </div>
            <div class="card mb-3">
              <div class="card-header">
                <i class="fas fa-table"></i>
                  Venta
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                      <tr>
                        <th class="text-center">#</th>
                        <th>Cliente</th>  
                        <th>Producto</th>             
                        <th>Cantidad</th>
                        <th>Precio Unitario</th>
                        <th>SubTotal</th>
                      </tr>
                    </thead>
                    <tbody id="tbBody">
                                
                    </tbody>
                    <tfoot>
                      <tr>
                        <th colspan="5" class="text-right">Sub Total</th>
                        <th class="text-center" id="subTotal">$ 0.00</th>
                      </tr>
                      <tr>
                        <th colspan="5" class="text-right">Total IVA</th>
                        <th class="text-center" id="iva">$ 0.00</th>
                      </tr>
                      <tr>
                        <th colspan="5" class="text-right">Contado</th>
                        <th class="text-center" id="contado">$ 0.00</th>
                      </tr>
                      <tr>
                        <th colspan="5" class="text-right">Crédito</th>
                        <th class="text-center" id="credito">$ 0.00</th>
                      </tr>
                      <tr>
                        <th colspan="5" class="text-right">Total</th>
                        <th class="text-center" id="total">$ 0.00</th>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            </div>
            <div class="form-group text-center">
              <br>
              <button id='aprobar' type="submit" onclick="sendData()" class='btn btn-primary' style="width: 30%" href='#'>Guardar</button>
              <button class='btn btn-secondary' onclick="javascript:history.back()" style="width: 30%" type='button'>Cancelar</button>                    
            </div>
          </div>
            <script>
              //Declarando variable globales
              var count = 0;
              var totalVenta = 0;
              var subTotalVenta = 0;
              var totalFila = 0;
              var cliente = "";
              //var totales = "";
              //var clientes = "";
              var cantidad = 0;
              var producto = "";
              var proporcion =  0;
              var codigoCliente = null;
              var contado = 0;
              var credito = 0;
              var isContado = true;
              var isCredito = false;
              
              function getCheckbox(){
                isContado = $("#id_is_contado").prop("checked");
                isCredito = $("#id_is_credito").prop("checked");
                if(isContado && isCredito){
                  $("#id_proporcion").removeAttr('disabled');
                  return true;
                }else{
                  $("#id_proporcion").val("");
                  $("#id_proporcion").attr('disabled','disabled');
                  proporcion = 0;
                  contado = 0;
                  credito = 0;
                  return false;
                }
              }
              function getData(){
                console.log("ADDROWS")
                count = count + 1;
                codigoCliente = $("#id_nombre_cliente").val();
                var cbCliente = document.getElementById("id_nombre_cliente");
                    
                cliente = cbCliente.options[cbCliente.selectedIndex].text;
                
                producto = $('#id_nombre_recurso').val();
                cantidad = parseInt($("#id_cantidad_detalle").val());
                var precio = parseFloat($("#id_costo_unitario_movimiento").val());
                if(getCheckbox()){
                  proporcion =  parseFloat($("#id_proporcion").val());
                }
                if(cliente!='' && cliente!='---------' && producto!='' && !isNaN(cantidad) && !isNaN(precio)){
                    addRows(cliente, producto, cantidad, precio);
                }
              };
              
              function addRows(cliente, producto, cantidad, precio){
                console.log("registro")
                totalFila=round(cantidad*precio);
                //totales+=totalFila+",";
                subTotalVenta=round((subTotalVenta+totalFila));
                iva=round(subTotalVenta*parseFloat({{impuesto.tasa_impuesto|stringformat:'f'}}));
                totalVenta=round(subTotalVenta*(1+parseFloat({{impuesto.tasa_impuesto|stringformat:'f'}})));
                if(isCredito && isContado){
                  credito = round(totalVenta*proporcion/100);
                  contado = round(totalVenta*(1-proporcion/100));
                }else{
                  if(isCredito){
                    credito = totalVenta;
                  }else{
                    contado = totalVenta;
                  }
                }
                //clientes+=codigoCliente+",";
                //cantidades+=cantidad+",";
                //productos+=producto+",";
                console.log("CANTIDAD");
                $("#tbBody").append(
                  "<tr><td class='text-center'>"+count+"</td>"+
                  "<td>"+cliente+"</td>"+
                  "<td>"+producto+"</td>"+
                  "<td class='text-center'>"+cantidad+"</td>"+
                  "<td class='text-center'>$ "+precio+"</td>"+
                  "<td class='text-center'>$ "+totalFila+"</td></tr>"
                );
                $("#subTotal").empty();
                $("#subTotal").append("$ "+subTotalVenta);
                $("#iva").empty();
                $("#iva").append("$ "+iva);
                $("#contado").empty();
                $("#contado").append("$ "+contado);
                $("#credito").empty();
                $("#credito").append("$ "+credito);
                $("#total").empty();
                $("#total").append("$ "+totalVenta);
              }
              function round(number){
                number = Math.round(number*100)/100;
                return number;
              };
              
            function sendData() {
              var data = {}
              if(totalVenta > 0){
                if(isCredito && isContado){
                  data = {
                    'totalVenta': subTotalVenta,
                    'totalFila': totalFila,
                    'cliente': cliente,
                    'producto': producto,
                    'cantidad': cantidad,
                    'proporcion': proporcion
                  }
                }else{
                  data = {
                    'totalVenta': subTotalVenta,
                    'totalFila': totalFila,
                    'cliente': cliente,
                    'producto': producto,
                    'cantidad': cantidad,
                    'isCredito': isCredito
                  }
                }
                $.ajax({
                  url: '{% url 'inventario:venta-crear' %}',
                  type: 'POST',
                  data: data,
                  success: function(data){
                    console.log(data);
                    console.log("SUCCESS");
                  },
                  dataType: 'json'
                }).done(function(data){
                  alert(data.message)
                  location.href = data.success_url;
                }).fail(function(data) {
                  console.log("error");
                  console.log(data.message);
                }).always(function() {
                  console.log("complete");
                });
              }
            }
          </script>
          </div>
        </div>
      </div>
    </div>
  {% endblock tables %}
{% endblock content %}

templates/inventario/gestionarClientes.html
{% extends 'header&footer.html' %}
{% block title %}SAeL - Gestión de Clientes{% endblock title %}

{% block content %}    
  {% block sidebar %}
    {% include 'sidebarInventario.html' %}
  {% endblock sidebar %}
  {% block tables %}
    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Listado de clientes</a>
          </li>
          <li class="breadcrumb-item active">Clientes</li>
        </ol>
        <!-- DataTables Example -->
        <div class="alert bold alert-info">
          <i class="fas fw fa-plus-circle"></i>
          <a href="{% url 'inventario:cliente-crear' %}">
            <strong>¡Click Aquí para agregar un nuevo cliente!</strong>
          </a>
        </div>
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Clientes
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                      <th>Codigo Cliente</th>
                      <th>Nombre Cliente</th>
                      <th>Nombre Titular Cliente</th>
                      <th>Operaciones</th>
                  </tr>
                </thead>
                <tbody>
                    {% for cliente in clientes %}
                        <tr id="{{ cliente.id_cliente }}">
                            <td class="text-center">{{ cliente.id_cliente }}</td>
                            <td>{{ cliente.nombre_cliente }}</td>
                            <td>{{ cliente.nombre_titular_cliente }}</td>
                            <td class="text-center">
                                <a class="fas fa-w fa-eye" name="ver" href="#"  data-toggle="modal" onclick="redirectView('CLIENTE', {{ cliente.id_cliente }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa-edit" name="editar" href="#" onclick="redirectEdit('CLIENTE', {{ cliente.id_cliente }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa fa-trash" name="eliminar" href="#" onclick="operacion({{ cliente.id_cliente }}, '{{ cliente.nombre_cliente }}', 'CLIENTE');" style="color:gray !important"></a>
                            </td>                          
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  {% endblock tables %}
    
{% endblock content %}

templates/inventario/gestionarCompras.html
{% extends 'header&footer.html' %}
{% block title %}SAeL - Gestión de compras{% endblock title %}

{% block content %}    
  {% block sidebar %}
    {% include 'sidebarInventario.html' %}
  {% endblock sidebar %}
  {% block tables %}
    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Listado de compras</a>
          </li>
          <li class="breadcrumb-item active">compras</li>
        </ol>
        <!-- DataTables Example -->
        <div class="alert bold alert-info">
          <i class="fas fw fa-plus-circle"></i>
          <a href="{% url 'inventario:compra-crear' %}">
            <strong>¡Click Aquí para agregar una nueva compra!</strong>
          </a>
        </div>
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            compras
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                      <th>Compra N°</th>
                      <th>Fecha</th>
                      <th>Total</th>
                      <th>Tipo</th>
                      <th>Operaciones</th>
                  </tr>
                </thead>
                <tbody>
                    {% for compra in compras %}
                        <tr id="{{ compra.id_compra }}" class="text-center">
                            <td class="text-center">{{ compra.id_compra }}</td>
                            <td>{{ compra.id_factura.transaccion.fecha_transaccion|date:"SHORT_DATE_FORMAT" }}</td>
                            <td>$ {{ compra.id_factura.total_factura }}</td>
                            {% if compra.id_factura.is_credito and compra.id_factura.is_contado %}
                              <td>Parcialmente al Credito</td>
                            {% elif compra.id_factura.is_credito %}
                              <td>Al Crédito</td>
                            {% elif compra.id_factura.is_contado %}
                              <td>Al Contado</td>
                            {% endif %}
                            <td class="text-center">
                                <a class="fas fa-w fa-eye" name="ver" href="#"  data-toggle="modal" onclick="redirectView('COMPRA', {{ compra.id_compra }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa-edit" name="editar" href="#" onclick="redirectEdit('COMPRA', {{ compra.id_compra }})" style="color:gray !important"></a>
                                <a class="fas fa-w fa fa-trash" name="eliminar" href="#" onclick="operacion({{ compra.id_compra }}, '{{ compra.id_cliente }}', 'COMPRA');" style="color:gray !important"></a>
                            </td>                          
                        </tr>
                    {% empty %}
                      <tr>
                        <td>Lo sentimos, no hay compras registradas</td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  {% endblock tables %}
    
{% endblock content %}